
services:
  # Node.js应用服务（开发环境）
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: trustpvp-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - trustpvp-network
    command: npm run dev

  # Redis数据库服务
  redis:
    image: redis:alpine
    container_name: trustpvp-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data-dev:/data
    networks:
      - trustpvp-network

networks:
  trustpvp-network:
    driver: bridge

volumes:
  redis-data-dev:
    driver: local 