FROM node:22

# 创建app目录
WORKDIR /app

# 安装nodemon用于热重载
RUN npm install -g nodemon

# 安装依赖
COPY package*.json ./
RUN npm install

# 复制应用代码
COPY . .

# 设置环境变量
ENV NODE_ENV=development
ENV PORT=3000

# 暴露端口
EXPOSE 3000

# 启动命令（使用nodemon监视文件变化）
CMD ["nodemon", "--legacy-watch", "index.js"] 